server:
  port: 8085
  servlet:
#jsp热部署
    jsp:
      init-parameters:
        development: ture

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aaa
    username: root
    password: 123456
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  redis:
    database: 0
    host: 192.168.241.110
    port: 6379
    jedis:
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8  # 连接池中的最大空闲连接
        min-idle: 0  # 连接池中的最小空闲连接
    timeout: 200  # 连接超时时间（毫秒）
    password:
#不能忘记配置
mybatis:
  mapper-locations: classpath:mapper/*.xml

